### ISSUE TITLE
what's going on in Antarctica?!

### ISSUE THREAD

**Issue by mkoo** [AmphibiaWeb/amphibian-disease-tracker#195] opened 2016-10-13 17:19 UTC
![screenshot-amphibiandisease org 2016-10-13 10-06-28](https://cloud.githubusercontent.com/assets/2523089/19359045/351e8e36-912d-11e6-93cf-2e474b709f0d.png)

Maybe need to allow multipart polygons for projects?

**Comment by tigerhawkvok** [comment] 2016-10-14 18:12
For what it's worth, https://amphibiandisease.org/project.php?id=6cb7107cb6ca3d148c982727a2cbfd3b seems to be a duplicate of https://amphibiandisease.org/project.php?id=76dca0082f14df0005eb16e142638c5a , except the first has the bad mcp.

**Comment by tigerhawkvok** [comment] 2016-10-18 05:27
We deleted the offending project last week

**Closed by tigerhawkvok** 2016-10-18 05:27 UTC
Labels: bug, Data Issue, project-viewing, wontfix
