### ISSUE TITLE
Add a toggle map layer for point data on Project Browser map for Diagnostic Labs

### ISSUE THREAD

**Issue by mkoo** [AmphibiaWeb/amphibian-disease-tracker#223] opened 2017-03-08 22:59 UTC
Data might be as KML or as Google Maps layer (MyMaps) or as Fusion Table layer

**Comment by mkoo** [comment] 2017-03-08 23:56
Adding feedback label: on second thought maybe just a simple table that we can update easily is all we need? Allow searches by state so people can find a lab close to them.

**Comment by tigerhawkvok** [comment] 2017-04-06 23:24
This is a duplicate of #150

**Closed** 2017-04-06 23:25 UTC
Labels: data, duplicate, mapping / gis, needs-feedback, project-viewing
